srcs/users/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import (
	MyViewSet,
    register_user,
    activate_user,
    dashboard,
    update_profile,
    change_password,
    invite_friend,
    accept_friend,
    friends_list,
    remove_friend,
)

app_name = 'users'

router = DefaultRouter()
router.register(r'myview', MyViewSet, basename='myview')

urlpatterns = [
    # Rotas de API usando FBV
    path('register/', register_user, name='register'),
    path('activate/<uidb64>/<token>/', activate_user, name='activate'),
    path('dashboard/', dashboard, name='dashboard'),
    path('update/', update_profile, name='update_profile'),
    path('change_password/', change_password, name='change_password'),
    path('add_friend/<int:user_id>/', invite_friend, name='add_friend'),
    path('accept_friend/<int:friendship_id>/', accept_friend, name='accept_friend'),
    path('friends/', friends_list, name='friends_list'),
    path('remove_friend/<int:user_id>/', remove_friend, name='remove_friend'),    # Rotas do roteador
    path('api/', include(router.urls)),
]

srcs/users/templates/users/activation_email.html
Hi {{ user.username }},

Thank you for registering. 
Please click the link below to activate your account:
https://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

srcs/users/templates/users/activation_invalid.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h2>Invalid Activation Link</h2>
	<br><br>
    <p>Sorry, the activation link is invalid or has expired.</p>
	<p>Please try registering again or contact support for assistance.</p>
  </div>
{% endblock %}

srcs/users/templates/users/activation_successful.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h2>Account Activated</h2>
	<br><br>
    <p>Your account has been successfully activated.</p>
	<p>You can now <a href="{% url 'auth:login' %}">log in</a> and participate in a Tournament.</p>
  </div>
{% endblock %}

srcs/users/templates/users/change_password.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h2>Change Password</h2>
	<br><br>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
  </div>
{% endblock %}

srcs/users/templates/users/dashboard.html
<!-- templates/users/dashboard.html -->
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  {% csrf_token %}
  <center>
	<h2>Bem-vindo {{ user.username }}!</h2>
	<br><br>
</center>
  <div class="row">
	<div class="column" style="background-color:#ccc;">
		<div class="mt-3">
			<p>&emsp;&emsp;<b>Avatar : </b> <img src="{{ user.avatar.url }}" alt="User Avatar" class="img-thumbnail" width="150" height="150"></p>
		</div>
		<p>&emsp;&emsp;<b>ID : </b> {{ user.id }}</p>
		<p>&emsp;&emsp;<b>Email : </b> {{ user.email }}</p>
		<p>&emsp;&emsp;<b>Nome : </b> {{ user.first_name }} {{ user.last_name }}</p>
		<p>&emsp;&emsp;<b>Username : </b> {{ user.username }}</p>
		<p>&emsp;&emsp;<b>Nickname : </b> {{ user.nickname }}</p>
		<p>&emsp;&emsp;<b>Registro em: </b> {{ user.date_joined }}</p>
		<p>&emsp;&emsp;<b>Último login em : </b> {{ user.last_login }}</p>
		<p>&emsp;&emsp;<b>Activo : </b> {{ user.is_active }}</p>
		<p>&emsp;&emsp;<b>Superusuário: </b> {{ user.is_superuser }}</p>
		<p>&emsp;&emsp;<b>Staff : </b> {{ user.is_staff }}</p>
		<center>
			<p><a href="{% url 'users:update_profile' %}">Update Profile</a></p>
		</center>
	</div>
	<div class="column" style="background-color:#eee;">
		{% include "users/friends_list.html" with friends=friends %}
	</div>
  </div>
  <center>
	<br><br>
    <form method="post" action="{% url 'auth:logout' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Logout</button>
    </form>
  </center>
{% endblock %}

srcs/users/templates/users/friends_list.html
{% block content %}
<div class="container mt-5">
	<center>
		<p><b>Friends List</b></p>
	</center>

	<br>
	<p>&emsp;&emsp;<b>Friends</b></p>
	<ul>
		{% for friend in friends %}
		  <li>
			{{ friend.username }} - {% if friend.online_status %}Online{% else %}Offline{% endif %}
			<form action="{% url 'users:remove_friend' user_id=friend.id %}" method="post" style="display:inline;">
			  {% csrf_token %}
			  <button type="submit" class="btn btn-danger btn-sm">Remove Friend</button>
			</form>
		  </li>
		{% endfor %}
	  </ul>
	  <p>You have {{ friends|length }} friend{{ friends|length|pluralize }}.</p>
  <hr>
  <p>&emsp;&emsp;<b>Pending Friend Requests Received</b></p>
<ul>
  {% for request in received_requests %}
    <li>
      {{ request.from_user.username }} - Requested by: {{ request.requested_by.username }} on {{ request.created_at }}
      <a href="{% url 'users:accept_friend' friendship_id=request.id %}">Accept</a>
    </li>
  {% endfor %}
</ul>
  
  <hr>
  <p>&emsp;&emsp;<b>Pending Friend Requests Sent</b></p>
  <ul>
    {% for request in sent_requests %}
      <li>
        {{ request.to_user.username }} (Pending) from {{ request.created_at }}
      </li>
    {% endfor %}
  </ul>

  <hr>
  <p>&emsp;&emsp;<b>Add Friends</b></p>
  <ul>
	{% for user in available_users %}
	  <li>
		{{ user.username }}
		<a href="{% url 'users:add_friend' user_id=user.id %}">Send Friend Request</a>
	  </li>
	{% endfor %}
  </ul>
  <hr>
</div>
{% endblock %}

srcs/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2>Profile</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Update Profile</button>
    </form>
  </div>
{% endblock %}

srcs/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Register</title>
</head>
<body>
    <div class="container mt-5">
        <h2>Register</h2>
        <form id="register-form">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" id="username" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
        <div id="message" class="mt-3"></div>
    </div>

    <script>
        document.getElementById('register-form').addEventListener('submit', function (event) {
            event.preventDefault();  // Previne o envio do formulário

            const username = document.getElementById('username').value;
            const email = document.getElementById('email').value;
            const password = document.getElementById('password').value;

            // Dados a serem enviados para o backend
            const data = {
                username: username,
                email: email,
                password: password
            };

            // Faz uma requisição POST para o endpoint da API de registro
            fetch('/users/api/register/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data)
            })
            .then(response => response.json())
            .then(data => {
                if (data.message) {
                    document.getElementById('message').innerHTML = '<div class="alert alert-success">' + data.message + '</div>';
                } else {
                    let errors = '';
                    for (let key in data) {
                        errors += `<p class="text-danger">${key}: ${data[key]}</p>`;
                    }
                    document.getElementById('message').innerHTML = errors;
                }
            })
            .catch((error) => {
                console.error('Error:', error);
                document.getElementById('message').innerHTML = '<div class="alert alert-danger">An error occurred while registering. Please try again later.</div>';
            });
        });
    </script>
</body>
</html>

srcs/users/templates/users/registration_complete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h2>Registration Complete</h2>
	<br><br>
    <p>Thank you for registering!</p>
	<p>A confirmation email has been sent to your email address.</p>
	<p>Please check your inbox and follow the link to activate your account.</p>
  </div>
{% endblock %}

srcs/users/templates/users/update_profile.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h2>Update Profile</h2>
	<br><br>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
	  <p><a href="{% url 'users:change_password' %}">Change Password</a></p>
      <button type="submit" class="btn btn-primary">Update</button>
    </form>
  </div>
{% endblock %}